/**
 * The legacy Russian abbreviation table. Formatting a reference lives in
 * `utils/scriptureReference.ts` — one reading of a reference's shape for the whole app.
 */

/**
 * Legacy abbreviations map for backward compatibility.
 * @deprecated Use getLocalizedAbbrev() from bibleData.ts instead
 */
export const BOOK_ABBREVIATIONS: Record<string, string> = {
  // Old Testament
  Genesis: 'Быт',
  Exodus: 'Исх',
  Leviticus: 'Лев',
  Numbers: 'Чис',
  Deuteronomy: 'Втор',
  Joshua: 'И.Нав',
  Judges: 'Суд',
  Ruth: 'Руф',
  '1 Samuel': '1Цар',
  '2 Samuel': '2Цар',
  '1 Kings': '3Цар',
  '2 Kings': '4Цар',
  '1 Chronicles': '1Пар',
  '2 Chronicles': '2Пар',
  Ezra: 'Езд',
  Nehemiah: 'Неем',
  Esther: 'Есф',
  Job: 'Иов',
  Psalms: 'Пс',
  Proverbs: 'Притч',
  Ecclesiastes: 'Еккл',
  'Song of Solomon': 'Песн',
  Isaiah: 'Ис',
  Jeremiah: 'Иер',
  Lamentations: 'Плач',
  Ezekiel: 'Иез',
  Daniel: 'Дан',
  Hosea: 'Ос',
  Joel: 'Иоил',
  Amos: 'Ам',
  Obadiah: 'Авд',
  Jonah: 'Ион',
  Micah: 'Мих',
  Nahum: 'Наум',
  Habakkuk: 'Авв',
  Zephaniah: 'Соф',
  Haggai: 'Агг',
  Zechariah: 'Зах',
  Malachi: 'Мал',
  // New Testament
  Matthew: 'Мф',
  Mark: 'Мк',
  Luke: 'Лк',
  John: 'Ин',
  Acts: 'Деян',
  Romans: 'Рим',
  '1 Corinthians': '1Кор',
  '2 Corinthians': '2Кор',
  Galatians: 'Гал',
  Ephesians: 'Еф',
  Philippians: 'Флп',
  Colossians: 'Кол',
  '1 Thessalonians': '1Фес',
  '2 Thessalonians': '2Фес',
  '1 Timothy': '1Тим',
  '2 Timothy': '2Тим',
  Titus: 'Тит',
  Philemon: 'Флм',
  Hebrews: 'Евр',
  James: 'Иак',
  '1 Peter': '1Пет',
  '2 Peter': '2Пет',
  '1 John': '1Ин',
  '2 John': '2Ин',
  '3 John': '3Ин',
  Jude: 'Иуд',
  Revelation: 'Откр',
};
