import type { SermonPoint } from "@/models/models";

interface BuildSectionOutlineMarkdownParams {
  orderedOutlinePoints: SermonPoint[];
  outlinePointsContentById: Record<string, string>;
}

export function buildSectionOutlineMarkdown({
  orderedOutlinePoints,
  outlinePointsContentById,
}: BuildSectionOutlineMarkdownParams): string {
  if (orderedOutlinePoints.length === 0) {
    return "";
  }

  return orderedOutlinePoints
    .map((outlinePoint) => {
      const pointContent = outlinePointsContentById[outlinePoint.id] ?? "";
      const header = `## ${outlinePoint.text}`;

      // If content already includes sub-point headings (generated by AI),
      // return as-is. Otherwise, add sub-point skeleton if sub-points exist
      // but no content has been generated yet.
      if (pointContent) {
        return `${header}\n\n${pointContent}`;
      }

      // No content yet — show sub-point skeleton for visual reference
      if (outlinePoint.subPoints && outlinePoint.subPoints.length > 0) {
        const sorted = [...outlinePoint.subPoints].sort((a, b) => a.position - b.position);
        const skeleton = sorted.map(sp => `### ${sp.text}`).join("\n\n");
        return `${header}\n\n${skeleton}`;
      }

      return `${header}\n\n${pointContent}`;
    })
    .join("\n\n");
}
